{
 "title": "Lido CSM Metrics Dashboard",
 "time": { "from": "now-5d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Community Staking Module Personal Node Operator Info:",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Node Operator Status",
   "type": "stat",
   "description": "is this Node Operator active ?",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_node_operator_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Added Keys",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_total_added_keys", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "fee to distribute",
   "type": "stat",
   "description": "claimable rewards",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lcoms_fee_to_distribute/1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fee Distributed",
   "type": "stat",
   "description": "already claimed rewards",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lcoms_fee_distributed_value / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unbonded Keys",
   "type": "stat",
   "description": "Number of unbonded keys",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_unbonded_keys", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deposited Keys",
   "type": "stat",
   "description": "total number of deposited keys",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_total_deposited_keys", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "deposited validators",
   "type": "stat",
   "description": "total deposited validators",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lcoms_total_deposited_validators",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vetted Keys",
   "type": "stat",
   "description": "total vetted keys",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_total_vetted_keys", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Withdrawn Keys",
   "type": "stat",
   "description": "total number of withdrawn keys",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_total_withdrawn_keys", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Exited Keys",
   "type": "stat",
   "description": "total number of exited keys",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_total_exited_keys", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validator Target",
   "type": "stat",
   "description": "Target number of validators",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_target_validators_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "target limit mode",
   "type": "stat",
   "description": "target limit mode",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_target_limit_mode", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "target limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_target_limit", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "depositable validators",
   "type": "stat",
   "description": "Count of depositable validators",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lcoms_depositable_validators_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stuck Validators",
   "type": "stat",
   "description": "Count of stuck validators",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_stuck_validators_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "end of stuck penalty",
   "type": "stat",
   "description": "Timestamp for end of stuck penalty",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lcoms_stuck_penalty_end_timestamp",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keys Enqueued",
   "type": "stat",
   "description": "Enqueued count",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_enqueued_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "required Bond for 1 new key",
   "type": "stat",
   "description": "Required stETH bond for the next key",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lcoms_required_bond_st_eth / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Metrics",
   "type": "timeseries",
   "description": "Balance of Validator",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{__name__=~\"^lcoms_validator_balance_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Bond",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "lcoms_current_bond / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locked Bond",
   "type": "stat",
   "description": "required bond",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lcoms_required_bond / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Excess Bond",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(lcoms_current_bond - lcoms_required_bond) / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "current bond shares",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "lcoms_current_bond_shares / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Locked Bond Shares",
   "type": "stat",
   "description": "required bond shares",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lcoms_required_bond_shares / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Excess bond shares",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(lcoms_current_bond_shares - lcoms_required_bond_shares) / 1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Exit Request Alert",
   "type": "stat",
   "description": "Exit Request Event",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_exit_request", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fee Distributed Alert",
   "type": "stat",
   "description": "fee distributed Event",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_fee_distributed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Slashing Alert",
   "type": "stat",
   "description": "initial slashing submitted Event",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lcoms_initial_slashing_submitted",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stealing Penalty Alert",
   "type": "stat",
   "description": "stealing penalty Event",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_stealing_penalty", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validator <32 Alert",
   "type": "stat",
   "description": "Validators below 32 ETH",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"^lcoms_validator_alert_.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator withdrawal Alert",
   "type": "stat",
   "description": "withdrawal submitted Event",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lcoms_withdrawal_submitted", "legendFormat": "__auto" }
   ]
  },
  { "title": "Alert metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Timestamp exit request",
   "type": "table",
   "description": "Timestamp of exit request event, labeled by index",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "lcoms_exit_request_timestamp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "stolen Amount",
   "type": "stat",
   "description": "EL rewards stealing penalty reported stolen amount",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lcoms_stealing_penalty_stolenAmount",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}