import clickInstallActions from "./actions.js";
import clickInstallGetters from "./getters.js";
import clickInstallMutations from "./mutations.js";

export default {
  state() {
    return {
      selectedNetworks: "",
      selectedPreset: [],
      testnetPlugins: [],
      mainnetPlugins: [],
      plugins: [
        {
          id: 1001,
          name: "GETH",
          network: "testnet",
          category: "execution",
          path: "/opt/stereum/geth",
          icon: require("../../../public/img/icon/plugin-icons/execution/Geth.png"),
        },
        {
          id: 1009,
          name: "HYPERLEDGER BESU",
          network: "testnet",
          category: "execution",
          path: "/opt/stereum/hyperledger",
          icon: require("../../../public/img/icon/plugin-icons/execution/hyperledger-besu.png"),
        },
        {
          id: 1008,
          name: "ERIGON",
          network: "testnet",
          category: "execution",
          path: "/opt/stereum/erigon",
          icon: require("../../../public/img/icon/plugin-icons/execution/Erigon.png"),
        },
        {
          id: 1010,
          name: "NETHERMIND",
          network: "testnet",
          category: "execution",
          path: "/opt/stereum/nethermind",
          icon: require("../../../public/img/icon/plugin-icons/execution/Nethermind.png"),
        },
        {
          id: 1011,
          name: "OPEN ETHEREUM",
          network: "testnet",
          category: "execution",
          path: "/opt/stereum/open-ethereum",
          icon: require("../../../public/img/icon/plugin-icons/execution/OpenEthereum.png"),
        },
        {
          id: 1002,
          name: "GRAFANA",
          network: "testnet",
          category: "service",
          path: "/opt/stereum/grafana",
          icon: require("../../../public/img/icon/plugin-icons/Other/grafana-service.png"),
        },
        {
          id: 1003,
          name: "LIGHTHOUSE",
          network: "testnet",
          category: "consensus",
          path: "/opt/stereum/lighthouse",
          icon: require("../../../public/img/icon/plugin-icons/consensus/LightHouse.png"),
        },
        {
          id: 1004,
          name: "LODESTAR",
          network: "testnet",
          category: "consensus",
          path: "/opt/stereum/lodestar",
          icon: require("../../../public/img/icon/plugin-icons/consensus/Lodestar.png"),
        },
        {
          id: 1005,
          name: "NIMBUS",
          network: "testnet",
          category: "consensus",
          path: "/opt/stereum/nimbus",
          icon: require("../../../public/img/icon/plugin-icons/consensus/Nimbus.png"),
        },
        {
          id: 1006,
          name: "TEKU",
          network: "testnet",
          category: "consensus",
          path: "/opt/stereum/teku",
          icon: require("../../../public/img/icon/plugin-icons/consensus/Teku.png"),
        },
        {
          id: 1007,
          name: "PRYSM",
          network: "testnet",
          category: "consensus",
          path: "/opt/stereum/prysm",
          icon: require("../../../public/img/icon/plugin-icons/consensus/Prysm.png"),
        },
        {
          id: 1012,
          name: "LIGHTHOUSE",
          network: "testnet",
          category: "validator",
          path: "/opt/stereum/lighthouse-validator",
          icon: require("../../../public/img/icon/plugin-icons/validator/lighthouse-validator.png"),
        },
        {
          id: 1013,
          name: "LOSESTAR",
          network: "testnet",
          category: "validator",
          path: "/opt/stereum/lodestar-validator",
          icon: require("../../../public/img/icon/plugin-icons/validator/lodestar-validator.png"),
        },
        {
          id: 1014,
          name: "PRYSM",
          network: "testnet",
          category: "validator",
          path: "/opt/stereum/prysm-validator",
          icon: require("../../../public/img/icon/plugin-icons/validator/prysm-validator.png"),
        },
        {
          id: 1015,
          name: "NIMBUS",
          network: "testnet",
          category: "validator",
          path: "/opt/stereum/prysm-validator",
          icon: require("../../../public/img/icon/plugin-icons/validator/nimbus-validator.png"),
        },
        {
          id: 1016,
          name: "TEKU",
          network: "testnet",
          category: "validator",
          path: "/opt/stereum/teku-validator",
          icon: require("../../../public/img/icon/plugin-icons/validator/teku-validator.png"),
        },
        {
          id: 1017,
          name: "BLOX SSV",
          network: "testnet",
          category: "service",
          path: "/opt/stereum/blox-ssv",
          icon: require("../../../public/img/icon/plugin-icons/Other/blox-ssv.png"),
        },
        {
          id: 1018,
          name: "EY NIGHTFALL",
          network: "testnet",
          category: "service",
          path: "/opt/stereum/ey-nightfall",
          icon: require("../../../public/img/icon/plugin-icons/Other/ey-nightfall.png"),
        },
        {
          id: 1019,
          name: "OBOL SSV",
          network: "testnet",
          category: "service",
          path: "/opt/stereum/obol-ssv",
          icon: require("../../../public/img/icon/plugin-icons/Other/obol-ssv.png"),
        },
        {
          id: 1020,
          name: "PROMETHEUS",
          network: "testnet",
          category: "service",
          path: "/opt/stereum/prometheus",
          icon: require("../../../public/img/icon/plugin-icons/Other/prometheus.png"),
        },
        {
          id: 1021,
          name: "ROCKETPOOL",
          network: "testnet",
          category: "service",
          path: "/opt/stereum/rocketpool",
          icon: require("../../../public/img/icon/plugin-icons/Other/rocketpool.png"),
        },
      ],
      presets: [
        {
          id: 1,
          name: "blox ssv",
          category: "execution",
          network: "testnet",
          networkIcon: require("../../../public/img/icon/click-installation/testnet-icon.png"),

          icon: require("../../../public/img/icon/click-installation/BLOX_SSV.png"),
          requirements: {
            core: 4,
            memory: 64,
          },
          includedPlugins: [],
        },
        {
          id: 2,
          name: "obol ssv",
          category: "execution",
          network: "mainnet",
          networkIcon: require("../../../public/img/icon/click-installation/mainnet-icon.png"),
          path: "/opt/stereumnode",
          icon: require("../../../public/img/icon/click-installation/OBOL_SSV.png"),
          requirements: {
            core: 4,
            memory: 64,
          },
        },
        {
          id: 3,
          name: "rocketpool",
          category: "execution",
          network: "testnet",
          networkIcon: require("../../../public/img/icon/click-installation/testnet-icon.png"),
          path: "/opt/stereumnode",
          icon: require("../../../public/img/icon/click-installation/rocketpool.png"),
          requirements: {
            core: 8,
            memory: 128,
          },
        },
        {
          id: 4,
          name: "obol ssv",
          category: "validator",
          network: "testnet",
          networkIcon: require("../../../public/img/icon/click-installation/mainnet-icon.png"),
          path: "/opt/stereumnode",
          icon: require("../../../public/img/icon/click-installation/OBOL_SSV.png"),
          requirements: {
            core: 4,
            memory: 64,
          },
        },
        {
          id: 5,
          name: "blox ssv",
          category: "execution",
          network: "mainnet",
          networkIcon: require("../../../public/img/icon/click-installation/testnet-icon.png"),
          path: "/opt/stereumnode",
          icon: require("../../../public/img/icon/click-installation/BLOX_SSV.png"),
          requirements: {
            core: 2,
            memory: 32,
          },
        },
        {
          id: 6,
          name: "rocketpool",
          category: "execution",
          network: "mainnet",
          networkIcon: require("../../../public/img/icon/click-installation/mainnet-icon.png"),
          path: "/opt/stereumnode",
          icon: require("../../../public/img/icon/click-installation/rocketpool.png"),
          requirements: {
            core: 8,
            memory: 64,
          },
        },
        {
          id: 7,
          name: "staking",
          category: "execution",
          networkIcon: require("../../../public/img/icon/click-installation/testnet-icon.png"),
          network: "testnet",
          mainPath: "/opt/stereumnode",
          icon: require("../../../public/img/icon/click-installation/staking-icon.png"),
          requirements: {
            core: 8,
            memory: 64,
          },
          includedPlugins: [],
        },
        {
          id: 8,
          name: "staking",
          network: "mainnet",
          mainPath: "/opt/stereumnode",
          networkIcon: require("../../../public/img/icon/click-installation/mainnet-icon.png"),
          icon: require("../../../public/img/icon/click-installation/staking-icon.png"),
          requirements: {
            core: 8,
            memory: 64,
          },
          includedPlugins: [],
        },
      ],
      systemInfos: {
        name: "Macbook",
        cpu: 4,
        memory: 128,
      },
    };
  },
  mutations: clickInstallMutations,
  actions: clickInstallActions,
  getters: clickInstallGetters,
};
