{
 "title": "Teku - Single",
 "description": "Dashboard to monitor a single Teku instance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "system", "label": "System", "query": "beacon_slot" }
  ]
 },
 "panels": [
  {
   "title": "VALIDATOR",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "1", "legendFormat": "VALIDATOR" }
   ]
  },
  {
   "title": "Local Validators",
   "type": "stat",
   "description": "Number of local validators",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "validator_local_validator_count"
    }
   ]
  },
  {
   "title": "Published Blocks",
   "type": "stat",
   "description": "Number of blocks published",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_beacon_node_published_block_total"
    }
   ]
  },
  {
   "title": "Published Attestations",
   "type": "stat",
   "description": "Number of attestations published",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_beacon_node_published_attestation_total"
    }
   ]
  },
  {
   "title": "Published Aggregates",
   "type": "stat",
   "description": "Number of aggregates published",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_beacon_node_published_aggregate_total"
    }
   ]
  },
  {
   "title": "Total Validators",
   "type": "stat",
   "description": "Total number of active validators in the network.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_active_validators"
    }
   ]
  },
  {
   "title": "Attestation Performance",
   "type": "graph",
   "description": "Percentage of attestations in each epoch with the correct head root, correct target root and that were successfully included in blocks.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "validator_performance_included_attestations / validator_local_validator_count",
     "legendFormat": "Included"
    },
    {
     "expr": "validator_performance_correct_head_block_count / validator_performance_included_attestations",
     "legendFormat": "Correct Head"
    },
    {
     "expr": "validator_performance_correct_target_count / validator_performance_included_attestations",
     "legendFormat": "Correct Target"
    }
   ]
  },
  {
   "title": "Attestation Inclusion Distance (slots)",
   "type": "graph",
   "description": "Number of slots between when an attestation is created to when it is included in a block. The minimum possible inclusion distance is 1.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "validator_performance_inclusion_distance_min",
     "legendFormat": "Minimum"
    },
    {
     "expr": "validator_performance_inclusion_distance_average",
     "legendFormat": "Average"
    },
    {
     "expr": "validator_performance_inclusion_distance_max",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Included Blocks",
   "type": "graph",
   "description": "Percentage of blocks produced in each epoch that were successfully included in the canonical chain.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "validator_performance_included_blocks / validator_performance_expected_blocks",
     "legendFormat": "Included Blocks"
    }
   ]
  },
  {
   "title": "BEACON CHAIN",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Current slot",
   "type": "stat",
   "description": "Current slot according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_slot" }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "description": "Current slot according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_slot" }
   ]
  },
  {
   "title": "Justified Epoch",
   "type": "stat",
   "description": "Current finalized epoch",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_current_justified_epoch" }
   ]
  },
  {
   "title": "Finalized Epoch",
   "type": "stat",
   "description": "Current finalized epoch",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_finalized_epoch" }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_peer_count" }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "The current epoch according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_epoch" }
   ]
  },
  {
   "title": "Slots Behind",
   "type": "stat",
   "description": "Number of slots the head block is behind.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "beacon_slot - beacon_head_slot" }
   ]
  },
  {
   "title": "Justification Delay (epochs)",
   "type": "stat",
   "description": "Number of epochs that justification has been delayed.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(beacon_epoch - beacon_current_justified_epoch - 1, 0)"
    }
   ]
  },
  {
   "title": "Finalisation Delay (epochs)",
   "type": "stat",
   "description": "Number of epochs that finalisation has been delayed.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(beacon_epoch - beacon_finalized_epoch - 2, 0)"
    }
   ]
  },
  {
   "title": "Correct Attestation Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_previous_correct_validators / beacon_previous_active_validators"
    }
   ]
  },
  {
   "title": "Trailing Distance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "beacon_slot - beacon_head_slot", "legendFormat": "Head Slot" },
    {
     "expr": "clamp_min(beacon_epoch - beacon_current_justified_epoch - 1, 0)",
     "legendFormat": "Justification Delay"
    },
    {
     "expr": "clamp_min(beacon_epoch - beacon_finalized_epoch - 2, 0)",
     "legendFormat": "Finalisation Delay"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "Number of slots between when an attestation is created to when it is included in a block. The minimum possible inclusion distance is 1.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "beacon_previous_live_validators / beacon_previous_active_validators",
     "legendFormat": "Live Validators"
    },
    {
     "expr": "beacon_previous_correct_validators / beacon_previous_active_validators",
     "legendFormat": "Correct Validators"
    }
   ]
  },
  {
   "title": "Gossip Messages",
   "type": "graph",
   "description": "Rate of gossip messages received per second.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(libp2p_gossip_messages_total[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "SYSTEM",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Percentage of attestations in each epoch with the correct head root, correct target root and that were successfully included in blocks.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_pool_bytes_used", "legendFormat": "{{job}} {{pool}} Used" },
    {
     "expr": "sum by (instance) (jvm_memory_pool_bytes_used)",
     "legendFormat": "{{job}} {{pool}} Used Total"
    },
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}} {{pool}} Process Total" },
    { "expr": " (jvm_memory_pool_bytes_max)", "legendFormat": "{{job}} {{pool}} Max" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "System Memory" }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}