{
 "title": "Lodestar - block processor",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "ByJob" }
  ]
 },
 "panels": [
  { "title": "Block processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block processor queue - Utilization rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(lodestar_block_processor_queue_job_time_seconds_sum[$rate_interval])",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Block processor queue - Jobs / slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "12*rate(lodestar_block_processor_queue_job_time_seconds_count[6m])",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Block processor queue - Job time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "delta(lodestar_block_processor_queue_job_time_seconds_sum[$rate_interval])/delta(lodestar_block_processor_queue_job_time_seconds_count[$rate_interval])",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Block processor queue - Dropped jobs %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "delta(lodestar_block_processor_queue_dropped_jobs_total[$rate_interval])/(delta(lodestar_block_processor_queue_job_time_seconds_count[$rate_interval])+delta(lodestar_block_processor_queue_dropped_jobs_total[$rate_interval]))",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Block processor queue - Job wait time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "delta(lodestar_block_processor_queue_job_wait_time_seconds_sum[$rate_interval])/delta(lodestar_block_processor_queue_job_wait_time_seconds_count[$rate_interval])",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Block processor queue - Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lodestar_block_processor_queue_length",
     "legendFormat": "block_processor"
    }
   ]
  },
  {
   "title": "Beacon state transition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Epoch transition avg time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_stfn_epoch_transition_seconds_sum[$rate_interval])\n/\ndelta(lodestar_stfn_epoch_transition_seconds_count[$rate_interval])",
       "legendFormat": "epoch transition"
      }
     ]
    },
    {
     "title": "Process block avg time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_stfn_process_block_seconds_sum[$rate_interval])/delta(lodestar_stfn_process_block_seconds_count[$rate_interval])",
       "legendFormat": "process block time"
      }
     ]
    },
    {
     "title": "Epoch transition utilization rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(lodestar_stfn_epoch_transition_seconds_sum[13m])",
       "legendFormat": "process block time"
      }
     ]
    },
    {
     "title": "Process block utilization rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(lodestar_stfn_process_block_seconds_sum[6m])",
       "legendFormat": "process block time"
      }
     ]
    },
    {
     "title": "Epoch transitions / epoch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "384 * rate(lodestar_stfn_epoch_transition_seconds_count[13m])",
       "legendFormat": "number of epoch transition"
      }
     ]
    },
    {
     "title": "process block / slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "12*rate(lodestar_stfn_process_block_seconds_count[6m])",
       "legendFormat": "process block time"
      }
     ]
    }
   ]
  },
  {
   "title": "BLS worker pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "About",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 29 },
     "options": {
      "content": "Verifies signature sets in a thread pool of workers. Must ensure that signatures are verified fast and efficiently."
     },
     "targets": [
      {
       "expr": "rate(lodestar_bls_thread_pool_time_seconds_sum[$rate_interval])",
       "legendFormat": "{{workerId}}"
      }
     ]
    },
    {
     "title": "BLS thread pool - utilization rate",
     "type": "timeseries",
     "description": "Utilization rate = total CPU time per worker per second. Graph is stacked. This ratios should be high since BLS verification is the limiting factor in the node's throughput.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(lodestar_bls_thread_pool_time_seconds_sum[$rate_interval])",
       "legendFormat": "{{workerId}}"
      }
     ]
    },
    {
     "title": "Aggregated pubkeys / sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "rate(lodestar_bls_aggregated_pubkeys_total[$rate_interval])",
       "legendFormat": "pubkeys / sec"
      }
     ]
    },
    {
     "title": "BLS thread pool - sig set verification time / set",
     "type": "timeseries",
     "description": "Average sync time to validate a single signature set. Note that the set may have been verified in batch. In most normal hardware this value should be ~1-2ms",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(delta(lodestar_bls_thread_pool_time_seconds_sum[$rate_interval]))/sum(delta(lodestar_bls_thread_pool_success_jobs_signature_sets_count[$rate_interval]))",
       "legendFormat": "pool"
      }
     ]
    },
    {
     "title": "BLS thread pool - sig sets / sec",
     "type": "timeseries",
     "description": "Raw throughput of the thread pool. How many individual signature sets are successfully validated per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(lodestar_bls_thread_pool_success_jobs_signature_sets_count[$rate_interval])",
       "legendFormat": "pool"
      }
     ]
    },
    {
     "title": "BLS thread pool - queue length",
     "type": "timeseries",
     "description": "Total length of the job queue. Note: this queue is not bounded",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lodestar_bls_thread_pool_queue_length",
       "legendFormat": "pool"
      }
     ]
    },
    {
     "title": "BLS thread pool - job wait time",
     "type": "timeseries",
     "description": "How much async time job spent waiting in the job queue before being picked up. This number should be really low <100ms to ensure signatures are validated fast.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_bls_thread_pool_queue_job_wait_time_seconds_sum[$rate_interval])/delta(lodestar_bls_thread_pool_queue_job_wait_time_seconds_count[$rate_interval])",
       "legendFormat": "pool"
      }
     ]
    },
    {
     "title": "BLS worker pool - to from worker latency",
     "type": "timeseries",
     "description": "Async time from sending a message to the worker and the worker receiving it.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(lodestar_bls_thread_pool_latency_to_worker_sum[6m])/delta(lodestar_bls_thread_pool_latency_to_worker_count[6m])",
       "legendFormat": "to worker"
      },
      {
       "expr": "delta(lodestar_bls_thread_pool_latency_from_worker_sum[6m])/delta(lodestar_bls_thread_pool_latency_from_worker_count[6m])",
       "legendFormat": "from worker"
      }
     ]
    },
    {
     "title": "BLS thread pool - % of sigs verified in batch",
     "type": "timeseries",
     "description": "What percentage of total signature sets were verified in batch, which is an optimization to reduce verification costs by x2. For a synced node this should be ~100%",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "delta(lodestar_bls_thread_pool_batch_sigs_success_total[$rate_interval])/delta(lodestar_bls_thread_pool_success_jobs_signature_sets_count[$rate_interval])",
       "legendFormat": "pool"
      }
     ]
    },
    {
     "title": "BLS worker pool - sigs per set",
     "type": "timeseries",
     "description": "Average signatures per set. This number is decided by the time of object submitted to the pool:\n- Sync blocks: 128\n- Aggregates: 3\n- Attestations: 1",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "delta(lodestar_bls_thread_pool_sig_sets_started_total[$rate_interval])/(delta(lodestar_bls_thread_pool_jobs_started_total[$rate_interval])>0)",
       "legendFormat": "pool"
      }
     ]
    },
    {
     "title": "BLS thread pool - Error rates",
     "type": "timeseries",
     "description": "How many individual signature sets are invalid vs (valid + invalid). We don't control this number since peers may send us invalid signatures. This number should be very low since we should ban bad peers. If it's too high the batch optimization may not be worth it.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "delta(lodestar_bls_thread_pool_error_jobs_signature_sets_count[$rate_interval])\n/\n(\n    delta(lodestar_bls_thread_pool_success_jobs_signature_sets_count[$rate_interval])\n    + delta(lodestar_bls_thread_pool_error_jobs_signature_sets_count[$rate_interval])\n)",
       "legendFormat": "sig_error_rate"
      },
      {
       "expr": "rate(lodestar_bls_thread_pool_batch_retries_total[$rate_interval])",
       "legendFormat": "batch_retries"
      }
     ]
    },
    {
     "title": "BLS worker pool - sets per job",
     "type": "timeseries",
     "description": "Average sets per job. A set may contain +1 signatures. This number should be higher than 1 to reduce communication costs",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "delta(lodestar_bls_thread_pool_jobs_started_total[$rate_interval])/delta(lodestar_bls_thread_pool_job_groups_started_total[$rate_interval])",
       "legendFormat": "pool"
      }
     ]
    }
   ]
  },
  {
   "title": "Precompute Epoch Transition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Run Result",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "32*12 * rate(lodestar_precompute_next_epoch_transition_result_total[13m])",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Hit vs Waste",
     "type": "timeseries",
     "description": "Cache Hit Count: number of state cache hit\nWaste Count: number of state that's not used",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "rate(lodestar_precompute_next_epoch_transition_hits_total[6m])",
       "legendFormat": "Cache Hit Count"
      },
      {
       "expr": "rate(lodestar_precompute_next_epoch_transition_waste_total[6m])",
       "legendFormat": "Waste Count"
      }
     ]
    },
    {
     "title": "Skip rate + error rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(lodestar_precompute_next_epoch_transition_result_total{result=\"skip\"}[13m]))\n/\nsum(rate(lodestar_precompute_next_epoch_transition_result_total[13m]))",
       "legendFormat": "skip rate"
      },
      {
       "expr": "sum(rate(lodestar_precompute_next_epoch_transition_result_total{result=\"error\"}[13m]))\n/\nsum(rate(lodestar_precompute_next_epoch_transition_result_total[13m]))",
       "legendFormat": "error rate"
      }
     ]
    },
    {
     "title": "Runs / epoch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "32*12 * sum(rate(lodestar_precompute_next_epoch_transition_result_total[13m]))",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fork-Choice Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "updateHead() avg time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "delta(beacon_fork_choice_find_head_seconds_sum[$rate_interval])/delta(beacon_fork_choice_find_head_seconds_count[$rate_interval])",
       "legendFormat": "find head"
      }
     ]
    },
    {
     "title": "updateHead() errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "beacon_fork_choice_errors_total"
      }
     ]
    },
    {
     "title": "updateHead() calls / slot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "12 * rate(beacon_fork_choice_find_head_seconds_count[$rate_interval])",
       "legendFormat": "updateHead calls"
      },
      { "legendFormat": "updateHead calls" },
      {
       "expr": "rate(beacon_fork_choice_find_head_seconds_sum[$rate_interval])",
       "legendFormat": "usage rate"
      }
     ]
    },
    {
     "title": "ratio of updateHead() calls that change head",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(beacon_fork_choice_changed_head_total[6m])/rate(beacon_fork_choice_requests_total[6m])",
       "legendFormat": "Changed Heads"
      },
      { "legendFormat": "Total Requests" }
     ]
    }
   ]
  }
 ]
}