{
 "title": "Lodestar - block production",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "ByJob" }
  ]
 },
 "panels": [
  { "title": "Block Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success + Error rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(beacon_block_production_successes_total[$rate_interval])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(beacon_block_production_requests_total[$rate_interval])\n-\nrate(beacon_block_production_successes_total[$rate_interval])",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Block production avg time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(beacon_block_production_seconds_sum[$rate_interval])\n/\nrate(beacon_block_production_seconds_count[$rate_interval])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Op-pool sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_size",
     "legendFormat": "aggregated_attestation"
    },
    {
     "expr": "lodestar_oppool_aggregated_attestation_pool_unique_data_count",
     "legendFormat": "aggregated_attestation_unique"
    },
    {
     "expr": "lodestar_oppool_attestation_pool_size",
     "legendFormat": "attestation"
    },
    {
     "expr": "lodestar_oppool_attester_slashing_pool_size",
     "legendFormat": "attester_slashing"
    },
    {
     "expr": "lodestar_oppool_proposer_slashing_pool_size",
     "legendFormat": "proposer_slashing"
    },
    {
     "expr": "lodestar_oppool_voluntary_exit_pool_size",
     "legendFormat": "voluntary_exit"
    },
    {
     "expr": "lodestar_oppool_sync_committee_message_pool_size",
     "legendFormat": "sync_committee_message"
    },
    {
     "expr": "lodestar_oppool_sync_contribution_and_proof_pool_pool_size",
     "legendFormat": "sync_contribution_and_proof"
    }
   ]
  },
  {
   "title": "Block production time histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(beacon_block_production_seconds_bucket[$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Builder API response times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(lodestar_api_rest_response_time_seconds_sum{operationId=~\"produceBlindedBlock|publishBlindedBlock|registerValidator\"}[$rate_interval])\n/\nrate(lodestar_api_rest_response_time_seconds_count{operationId=~\"produceBlindedBlock|publishBlindedBlock|registerValidator\"}[$rate_interval])",
     "legendFormat": "{{operationId}}"
    }
   ]
  },
  {
   "title": "Builder API queries / slot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "12 * rate(lodestar_api_rest_response_time_seconds_count{operationId=~\"produceBlindedBlock|publishBlindedBlock|registerValidator\"}[$rate_interval])",
     "legendFormat": "{{operationId}}"
    }
   ]
  }
 ]
}