{
 "title": "Validator Ejector",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Exit Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exit Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_exit_messages{}"
    }
   ]
  },
  {
   "title": "Invalid Exit Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_exit_messages{valid=\"false\"}"
    }
   ]
  },
  {
   "title": "Exit Messages Left",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((validator_ejector_exit_messages{valid=\"true\"} OR vector(0)) / 100 * on() (validator_ejector_exit_actions{result=\"success\"} OR validator_ejector_exit_messages{valid=\"true\"} OR vector(0)))"
    }
   ]
  },
  {
   "title": "Exit Messages Left",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_exit_messages{valid=\"true\"} - on() (validator_ejector_exit_actions{result=\"success\"} OR vector(0)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Exit Actions Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_exit_actions{result=\"success\"}"
    }
   ]
  },
  {
   "title": "Exit Action Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_exit_actions{result=\"error\"}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Successful Jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_job_duration_seconds_bucket{le=\"+Inf\",result=\"success\"}"
    }
   ]
  },
  {
   "title": "Job Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_job_duration_seconds_bucket{le=\"+Inf\",result=\"error\"}"
    }
   ]
  },
  {
   "title": "Jobs Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(validator_ejector_job_duration_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Job Time Interval",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_job_duration_seconds_bucket{le=\"+Inf\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Execution Node Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(validator_ejector_execution_request_duration_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Execution Node Request Average Duration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_execution_request_duration_seconds_sum/validator_ejector_execution_request_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Consensus Node Request Average Duration",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_ejector_consensus_request_duration_seconds_sum/validator_ejector_consensus_request_duration_seconds_count"
    }
   ]
  }
 ]
}