{
 "title": "Node Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "instance", "query": "ssv_beacon_status" }
  ]
 },
 "panels": [
  { "title": "Node Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Health Status",
   "type": "gauge",
   "description": "Current status of the beacon, ETH1 and SSV operator node",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv_beacon_status{instance=~\"$instance.*\"}",
     "legendFormat": "Beacon"
    },
    {
     "expr": "ssv_eth1_status{instance=~\"$instance.*\"}",
     "legendFormat": "ETH1"
    },
    {
     "expr": "(ssv_node_status{instance=~\"$instance.*\"} + 1) or (absent(ssv_node_status{instance=~\"$instance.*\"}) * 0)",
     "legendFormat": "SSV Operator"
    }
   ]
  },
  {
   "title": "Beacon Node Health",
   "type": "timeseries",
   "description": "Health status of the beacon node",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ssv_beacon_status{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "ETH1 Node Health",
   "type": "timeseries",
   "description": "Health status of the ETH1 node",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "ssv_eth1_status{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "SSV Operator Node Health",
   "type": "timeseries",
   "description": "Health status of the SSV operator node",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ssv_node_status{instance=~\"$instance.*\"} + 1",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "absent(ssv_node_status{instance=~\"$instance.*\"}) * 0"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Memory Usage (RAM)",
   "type": "graph",
   "description": "RAM memory usage of the SSV operator node",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\", pod=~\"$instance.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory (Go)",
   "type": "timeseries",
   "description": "Go memory usage of the SSV operator node",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "sys_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance.*\"}",
     "legendFormat": "stack_inuse_bytes"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Number of go routines running on the SSV operator node",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "CPU usage of the SSV operator node",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Hard drive memory usage of the SSV operator node",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=\"$instance\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Network I/O (1m rate)",
   "type": "timeseries",
   "description": "Network input and output usage of the SSV operator node",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "in {{pod}}"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{pod=~\"$instance.*\"}[1m])) by (pod)",
     "legendFormat": "out {{pod}}"
    }
   ]
  },
  { "title": "Network Discovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Connected Peers",
   "type": "stat",
   "description": "Number of connected peers to the SSV operator node",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssv_p2p_all_connected_peers{instance=~\"$instance.*\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  {
   "title": "Subnet Peers Distribution ",
   "type": "timeseries",
   "description": "Subnet peer distribution based on topic",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ssv_p2p_connected_peers{instance=~\"$instance.*\"}",
     "legendFormat": "{{pubKey}}"
    }
   ]
  },
  {
   "title": "Subnets Peers Count",
   "type": "table",
   "description": "Subnet peers breakdown table of the SSV operator node",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "ssv:network:subnets:known{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:network:subnets:connected{instance=~\"$instance.*\"}"
    },
    {
     "expr": "ssv:network:subnets:my{instance=~\"$instance.*\"}"
    }
   ]
  },
  {
   "title": "Peers Discovery Rate",
   "type": "timeseries",
   "description": "The discovery rate of the subnet peers.\nFound is rate per second of nodes that were found with discovery. Rejected is rate per second of nodes that were found with discovery but rejected because of limit or subnet",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "rate(ssv:network:discovery:found{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "Found"
    },
    {
     "expr": "rate(ssv:network:discovery:rejected{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table",
   "description": "Table breakdown of all the SSV operator nodes",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "index" } },
   "targets": [
    {
     "expr": "rate(ssv:network:peers_identity{instance=~\"$instance.*\"}[5m])"
    }
   ]
  },
  { "title": "Network Messaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Pubsub Messages RPS (5m rate)",
   "type": "timeseries",
   "description": "Rate per second of inbound / outbound topic messages over the last 5 minutes",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum (rate(ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "inbound"
    },
    {
     "expr": "sum (rate(ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\", msg_type=\"0\"}[5m]))",
     "legendFormat": "inbound SSVConsensusMsgType"
    },
    {
     "expr": "sum (rate(ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\", msg_type=\"1\"}[5m]))",
     "legendFormat": "inbound SSVPartialSignatureMsgType"
    },
    {
     "expr": "sum (rate(ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\", msg_type=\"2\"}[5m]))",
     "legendFormat": "inbound DKGMsgType"
    },
    {
     "expr": "sum (rate(ssv:p2p:pubsub:msg:out{instance=~\"$instance.*\"}[5m]))",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Incoming Pubsub Messages RPS (5m rate)",
   "type": "timeseries",
   "description": "Rate per second of incoming topic messages for every topic over the last 5 minutes",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate (ssv:p2p:pubsub:msg:in{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing Pubsub Messages RPS (5m rate)",
   "type": "timeseries",
   "description": "Rate per second of outgoing topic messages for every topic over the last 5 minutes.\nResponses are outgoing, for incoming requests.\nSuccessful Requests are outgoing.\nActive are outgoing requests.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate (ssv:p2p:pubsub:msg:out{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Stream Protocols (table)",
   "type": "table",
   "description": "Table breakdown for each stream protocol.\nResponses are outgoing, for incoming requests.\nSuccessful Requests are outgoing.\nActive Requests are outgoing.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "ssv:p2p:streams:res{instance=~\"$instance.*\"}",
     "legendFormat": "Outgoing Responses"
    },
    {
     "expr": "ssv:p2p:streams:req:count{instance=~\"$instance.*\"}",
     "legendFormat": "Requests"
    },
    {
     "expr": "ssv:p2p:streams:req:success{instance=~\"$instance.*\"}",
     "legendFormat": "Successful Outgoing Requests"
    },
    {
     "expr": "ssv:p2p:streams:req:active{instance=~\"$instance.*\"}",
     "legendFormat": "Active Outgoing Requests"
    }
   ]
  },
  {
   "title": "Stream Protocols (time-series)",
   "type": "timeseries",
   "description": "Rate per second of requests,  responses and active requests.\nResponses are outgoing, for incoming requests.\nSuccessful Requests are outgoing.\nActive are outgoing requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rate(ssv:p2p:streams:res{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "Responses {{pid}}"
    },
    {
     "expr": "rate(ssv:p2p:streams:req:count{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "Requests {{pid}}"
    },
    {
     "expr": "rate(ssv:p2p:streams:req:success{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "Successful Requests {{pid}}"
    },
    {
     "expr": "rate(ssv:p2p:streams:req:active{instance=~\"$instance.*\"}[5m])",
     "legendFormat": "Active {{pid}}"
    }
   ]
  }
 ]
}