{
 "title": "ssv.network Operator Node",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "explorer",
    "query": "https://explorer.stage.ssv.network,https://explorer.ssv.network"
   },
   { "name": "validator_dashboard_id", "query": "XIbEQ37aa" }
  ]
 },
 "panels": [
  {
   "title": "Network Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Subnets Peers Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "expr": "ssv:network:subnets:known" },
    { "expr": "ssv:network:subnets:connected" },
    { "expr": "ssv:network:subnets:my" }
   ]
  },
  {
   "title": "Total Connections Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "ssv:network:all_connected_peers",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Peers Discovery Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(ssv:network:discovery:found[2m])",
     "legendFormat": "Found"
    },
    {
     "expr": "rate(ssv:network:discovery:rejected[2m])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "DiscV5 Ping/Pong",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 10 },
   "targets": [
    { "expr": "ssv:network:discovery:enr_ping", "legendFormat": "Ping" },
    { "expr": "ssv:network:discovery:enr_pong", "legendFormat": "Pong" }
   ]
  },
  {
   "title": "Topics Peers Distribution ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 19 },
   "targets": [
    { "expr": "ssv:network:connected_peers", "legendFormat": "{{pubKey}}" }
   ]
  },
  {
   "title": "Network Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network I/O (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 15, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total[1m])) by (pod)",
       "legendFormat": "in {{pod}}"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total[1m])) by (pod)",
       "legendFormat": "out {{pod}}"
      }
     ]
    },
    {
     "title": "Pubsub Messages (2m rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum (rate(ssv:p2p:pubsub:msg:in[2m]))",
       "legendFormat": "inbound"
      },
      {
       "expr": "sum (rate(ssv:p2p:pubsub:msg:out[2m]))",
       "legendFormat": "outbound"
      }
     ]
    },
    {
     "title": "Pubsub Message Validation Result",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 11 },
     "targets": [
      {
       "expr": "rate (ssv:network:pubsub:msg:validation[2m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Incoming Topic Messages (2m rate)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate (ssv:p2p:pubsub:msg:in[2m])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Outgoing Topic Messages (2m rate)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 11, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate (ssv:p2p:pubsub:msg:out[2m])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Pubsub Trace distribution (2m rate)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "rate(ssv:network:pubsub:trace[2m])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Stream Protocols",
     "type": "table",
     "gridPos": { "h": 10, "w": 9, "x": 13, "y": 31 },
     "targets": [
      { "expr": "ssv:p2p:streams:res", "legendFormat": "Responses" },
      { "expr": "ssv:p2p:streams:req:count", "legendFormat": "Requests" },
      { "expr": "ssv:p2p:streams:req:success", "legendFormat": "Successful Requests" },
      { "expr": "ssv:p2p:streams:req:active", "legendFormat": "Active" }
     ]
    }
   ]
  },
  {
   "title": "Validators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Validator Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "count(ssv:validator:status == 3)",
     "legendFormat": "Active"
    },
    { "expr": "count(ssv:validator:status)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Change Round Distribution ",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssv:validator:ibft_stage == 4)",
     "legendFormat": "All Change Round"
    },
    {
     "expr": "count(ssv:validator:ibft_round > 2)",
     "legendFormat": "Total Above Round 2"
    },
    {
     "expr": "count_values(\"round\", ssv:validator:ibft_round > 2)",
     "legendFormat": "round {{ round }}"
    }
   ]
  },
  {
   "title": "Change Round",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 14, "y": 32 },
   "targets": [
    {
     "expr": "count(ssv:validator:ibft_stage == 4)",
     "legendFormat": "All Change Round"
    }
   ]
  },
  {
   "title": "Validators (Attestation)",
   "type": "table",
   "description": "Information on attestation duties for all validators registered to an operator",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 42 },
   "targets": [
    { "expr": "ssv:validator:ibft_stage" },
    {
     "expr": "ssv:validator:ibft_highest_decided"
    },
    { "expr": "ssv:network:connected_peers" },
    {
     "expr": "ssv:validator:ibft_current_sequence"
    },
    { "expr": "ssv:validator:ibft_round" },
    {
     "expr": "ssv:validator:running_ibfts_count"
    },
    {
     "expr": "ssv:validator:ibft_current_slot"
    },
    { "expr": "ssv:validator:status" }
   ]
  },
  {
   "title": "QBFT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Processed Messages by Workers (2m rate)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "rate (ssv:worker:msg:process[2m])",
       "legendFormat": "Processed Messages Rate"
      }
     ]
    },
    {
     "title": "QBFT Message Queues",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 11, "y": 4 },
     "targets": [
      {
       "expr": "sum by (v) (ssv:ibft:msgq:ratio)",
       "legendFormat": "Messages"
      }
     ]
    },
    {
     "title": "QBFT Message Queue Size",
     "type": "table",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 14 },
     "targets": [
      { "expr": "ssv:ibft:msgq:ratio" }
     ]
    },
    {
     "title": "QBFT Message Queue Size (Types)",
     "type": "table",
     "gridPos": { "h": 11, "w": 17, "x": 0, "y": 24 },
     "targets": [
      { "expr": "ssv:ibft:msgq:ratio" }
     ]
    }
   ]
  },
  {
   "title": "Operators",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version Distribution",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 57 },
   "targets": [
    { "expr": "ssv:network:peers_identity" }
   ]
  },
  {
   "title": "Known Operators",
   "type": "table",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 69 },
   "targets": [
    { "expr": "ssv:network:peers_identity" },
    { "expr": "ssv:exporter:operator_index{}" }
   ]
  },
  {
   "title": "Node Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Health Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ssv:beacon:node_status", "legendFormat": "Beacon" },
    { "expr": "ssv:eth1:node_status", "legendFormat": "ETH1" },
    { "expr": "ssv:node_status", "legendFormat": "SSV Operator" },
    {}
   ]
  },
  {
   "title": "Operator Node Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "ssv:node_status", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "ETH1 Node Health",
   "type": "timeseries",
   "description": "Status of the connected ETH1 node",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 83 },
   "targets": [
    { "expr": "ssv:eth1:node_status" }
   ]
  },
  {
   "title": "Beacon Node Health",
   "type": "timeseries",
   "description": "Status of the connected beacon node",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 83 },
   "targets": [
    { "expr": "ssv:beacon:node_status" }
   ]
  },
  {
   "title": "Process Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory (Go)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "go_memstats_sys_bytes", "legendFormat": "sys_bytes" },
      { "expr": "go_memstats_heap_idle_bytes", "legendFormat": "heap_idle_bytes" },
      { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "heap_inuse_bytes" },
      { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "stack_inuse_bytes" }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Memory Usage (k8s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 139 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 139 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_goroutines", "legendFormat": "{{ pod }}" }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Network I/O (1m rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total[1m])) by (pod)",
       "legendFormat": "in {{pod}}"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total[1m])) by (pod)",
       "legendFormat": "out {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}