import { defineStore } from "pinia";

export const useNodeStore = defineStore("theNode", {
  state: () => {
    return {
      pingQuality: [
        {
          id: 1,
          maxRate: 20,
          status: "excellent",
          description: "Excellent connection quality with very low latency.",
        },
        {
          id: 2,
          maxRate: 50,
          status: "good",
          description: "Good connection quality with low latency.",
        },
        {
          id: 3,
          maxRate: 150,
          status: "fair",
          description: "Fair connection quality with moderate latency.",
        },
        {
          id: 4,
          maxRate: 200,
          status: "poor",
          description: "Poor connection quality with high latency.Try reconnecting to the node.",
        },
        {
          id: 5,
          maxRate: Infinity,
          status: "very poor",
          description: "Very poor connection quality with high latency.Try reconnecting to the node.",
        },
      ],
      pingHistory: [],
      connectionStatus: null,
      connectionStatusIsPoor: false,
      skeletonLoading: false,
      lines: [],
      isLineHidden: false,
      lineOne: null,
      lineTwo: null,
      lineThree: null,
      sinceDateParsDays: 0,
      untilDateParsDays: 0,
      exportLogsType: "",
      infoAlarm: true,
      runNodePowerModal: false,
      clientToLogs: null,
      logs: [],
      allLogsForExp: false,
      isLogLoading: false,
      isExportCustomizedDateLoading: false,
      exportLogs: false,
      searchLogs: "",
      logTail: null,
      serviceLogs: [],
      consensusItems: [],
      executionItems: [],
      validatorItems: [],
      servicePlugins: [],
      sidebarPlugins: [
        {
          id: 1,
          source: require("../../public/img/icon/edit-node-icons/filter-confirmed.png"),
          drag: true,
          category: "execution",
          active: false,
        },
        {
          id: 2,
          source: require("../../public/img/icon/edit-node-icons/service-item-icon.png"),
          drag: true,
          category: "consensus",
          active: false,
        },
        {
          id: 3,
          source: require("../../public/img/icon/edit-node-icons/service-item-icon.png"),
          drag: true,
          category: "service",
          active: false,
        },
        {
          id: 4,
          source: require("../../public/img/icon/edit-node-icons/service-item-icon.png"),
          drag: true,
          category: "validator",
          active: false,
        },
        {
          id: 5,
          source: require("../../public/img/icon/edit-node-icons/service-item-icon.png"),
          drag: true,
          category: "validator",
          active: false,
        },
        {
          id: 6,
          source: require("../../public/img/icon/edit-node-icons/service-item-icon.png"),
          drag: true,
          category: "service",
          active: false,
        },
        {
          id: 7,
          source: require("../../public/img/icon/edit-node-icons/service-item-icon.png"),
          drag: true,
          category: "consensus",
          active: false,
        },
        {
          id: 8,
          source: require("../../public/img/icon/edit-node-icons/service-item-icon.png"),
          drag: true,
          category: "execution",
          active: false,
        },
        {
          id: 9,
          source: require("../../public/img/icon/edit-node-icons/service-item-icon.png"),
          drag: true,
          category: "service",
          active: false,
        },
        {
          id: 10,
          source: require("../../public/img/icon/edit-node-icons/service-item-icon.png"),
          drag: true,
          category: "consensus",
          active: false,
        },
      ],
      statusContents: [
        {
          id: 1,
          status: "red",
        },
        {
          id: 2,
          status: "yellow",
        },
        {
          id: 3,
          status: "red",
        },
        {
          id: 4,
          status: "yellow",
        },
        {
          id: 3,
          status: "red",
        },
        {
          id: 4,
          status: "yellow",
        },
      ],

      ssvNetworkUrl: {
        operatorUrl: "https://www.google.com/",
        grafanaDashboardUrl: "https://www.google.com",
      },
    };
  },
  getters: {},
  actions: {},
});
