{
 "title": "multiple source",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus Node", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_cpu_seconds_total,job)"
   },
   { "name": "beacon", "label": "Beacon Node", "query": "label_values(beacon_slot,job)" },
   {
    "name": "validator",
    "label": "Validator Node",
    "query": "label_values(validator_balance,job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Beacon Chain",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Local Beacon Chain",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Network Validators",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 9, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Slots/Epochs",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "stat",
   "description": "The percentage of ETH balances expected to attest that are actually attesting.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"beacon node\"} / beacon_prev_epoch_active_gwei{job=\"beacon node\"} )"
    }
   ]
  },
  {
   "title": "Network Liveness",
   "type": "stat",
   "description": "A metric expressing the distance between the current finalized epoch and the expected finalized epoch based on the genesis time. 100% means the expected and current finalized epochs are the same. The metric reaches 0% when the finalized epoch is 25 epochs behind the expected epoch.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1-(4*((floor(beacon_clock_time_slot{job=\"$beacon\"}/32) - beacon_finalized_epoch{job=\"$beacon\"} - 2)/100))),0)"
    }
   ]
  },
  {
   "title": "Beacon Uptime",
   "type": "singlestat",
   "description": "The length of time the beacon chain process has been running",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$beacon\"})/3600"
    }
   ]
  },
  {
   "title": "Beacon Log Messages",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"$beacon\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"$beacon\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Validator Counts",
   "type": "stat",
   "description": "Counts of active, slashed and exited validators.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Active\",job=\"$beacon\"} ",
     "legendFormat": "active"
    },
    {
     "expr": "validator_count{state=\"Slashed\",job=\"$beacon\"} ",
     "legendFormat": "slashed"
    },
    {
     "expr": "validator_count{state=\"Exited\",job=\"$beacon\"} ",
     "legendFormat": "exited"
    }
   ]
  },
  {
   "title": "Validator Queues",
   "type": "stat",
   "description": "Current number of pending and exiting validators",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",job=\"$beacon\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",job=\"$beacon\"}",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Queue Lengths",
   "type": "stat",
   "description": "Estimated length of time until all pending and exiting validators have cleared the queues.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((validator_count{state=\"Pending\",job=\"$beacon\"}/4)*6.4)",
     "legendFormat": "pending"
    },
    {
     "expr": "((validator_count{state=\"Exiting\",job=\"$beacon\"}/4)*6.4)",
     "legendFormat": "exiting"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "stat",
   "description": "Current, justified, and finalized epochs. In this order, these three values should be sequentially decreasing.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(beacon_clock_time_slot{job=\"$beacon\"} / 32)",
     "legendFormat": "current"
    },
    {
     "expr": "beacon_current_justified_epoch{job=\"$beacon\"}",
     "legendFormat": "justified"
    },
    {
     "expr": "beacon_finalized_epoch {job=\"$beacon\"} ",
     "legendFormat": "finalized"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "The percentage of ETH balances expected to attest that are actually attesting.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit", "label": "Participation Rate" }
   ],
   "targets": [
    {
     "expr": "(beacon_prev_epoch_target_gwei{job=\"beacon node\"} / beacon_prev_epoch_active_gwei{job=\"beacon node\"} )",
     "legendFormat": "participation rate"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "The number of peers to which the beacon chain is connected",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\",job=\"$beacon\"}",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Avg. Balance",
   "type": "singlestat",
   "description": "Average validator balance across the network",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\",job=\"$beacon\"} / validator_count{state=\"Active\",job=\"$beacon\"} / 1000000000",
     "legendFormat": "eth"
    }
   ]
  },
  {
   "title": "Validators",
   "type": "graph",
   "description": "Number of pending and existing validators over time. Pending validators are shown as positive values, while exiting validators are shown as negative values.",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "validators" }
   ],
   "targets": [
    {
     "expr": "validator_count{state=\"Pending\",job=\"$beacon\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "validator_count{state=\"Exiting\",job=\"$beacon\"}",
     "legendFormat": "exiting"
    },
    {
     "expr": "validator_count{state=\"Slashing\",job=\"$beacon\"}",
     "legendFormat": "slashing"
    },
    {
     "expr": "validator_count{job=\"$beacon\", state=\"Active\"}",
     "legendFormat": "active validators"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "stat",
   "description": "Current slot and head slot",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "beacon_slot{job=\"$beacon\"}",
     "legendFormat": "current slot"
    },
    {
     "expr": "beacon_head_slot{job=\"$beacon\"}",
     "legendFormat": "head slot"
    }
   ]
  },
  {
   "title": "Stake Effectiveness",
   "type": "singlestat",
   "description": "The percentage of all validator balances earning returns. Equal to effective balance of all validators divided by the total balance of all validators.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "validators_total_effective_balance{job=\"$beacon\",state=\"Active\"}/validators_total_balance{job=\"$beacon\",state=\"Active\"}"
    }
   ]
  },
  {
   "title": "Slots Behind",
   "type": "singlestat",
   "description": "The difference between the expected slot based on the genesis time and the current head slot. Ideally this is zero.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot{job=\"$beacon\"}",
     "legendFormat": "slots"
    }
   ]
  },
  {
   "title": "Server",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Local Validators",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes", "label": "GB" }
   ],
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{job=\"$host\"} - node_memory_MemFree_bytes{job=\"$host\"} - node_memory_Buffers_bytes{job=\"$host\"} - node_memory_Cached_bytes{job=\"$host\"} - node_memory_SwapCached_bytes{job=\"$host\"} - node_memory_Slab_bytes{job=\"$host\"} - node_memory_PageTables_bytes{job=\"$host\"} - node_memory_VmallocUsed_bytes{job=\"$host\"} ) or ( node_memory_MemTotal{job=\"$host\"} - node_memory_MemFree{job=\"$host\"} - node_memory_Buffers{job=\"$host\"} - node_memory_Cached{job=\"$host\"} - node_memory_SwapCached{job=\"$host\"} - node_memory_Slab{job=\"$host\"} - node_memory_PageTables{job=\"$host\"} - node_memory_VmallocUsed{job=\"$host\"} )",
     "legendFormat": "apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"$host\"} or node_memory_Buffers{job=\"$host\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"$host\"} or node_memory_Cached{job=\"$host\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"$host\"} or node_memory_MemFree{job=\"$host\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_Slab_bytes{job=\"$host\"} or node_memory_Slab{job=\"$host\"}",
     "legendFormat": "slab"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Network transmission (tx) and reception (rx) rates",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$host\",device='eth0'}[5m])*8",
     "legendFormat": "tx"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$host\",device='eth0'}[5m])*8 ",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "The length of time the validator process has been running",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$validator\"})/3600"
    }
   ]
  },
  {
   "title": "Validator Log Messages",
   "type": "stat",
   "description": "Average number of log messages received per hour over the selected time range",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "/hr" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(log_entries_total{job=\"$validator\", level=\"error\"}[$__range]))*3600",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(rate(log_entries_total{job=\"$validator\", level=\"warning\"}[$__range]))*3600",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Total Earnings  (ETH)",
   "type": "singlestat",
   "description": "Total ETH return on the initial effective stake of active local validators.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"$validator\"})-(count(validator_balance{job=\"$validator\"} > 16 and validator_statuses{job=\"$validator\"} == 3)*32)"
    }
   ]
  },
  {
   "title": "Total Return",
   "type": "singlestat",
   "description": "Total percentage return on the initial effective stake of active local validators. Excess deposits will be reflected as earnings.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(validator_balance{job=\"$validator\"}) - (count(validator_balance{job=\"$validator\"} > 16 and validator_statuses{job=\"$validator\"} == 3)*32))/(count(validator_balance{job=\"$validator\"} > 16 and validator_statuses{job=\"$validator\"} == 3)*32)  "
    }
   ]
  },
  {
   "title": "Validator Process Stats",
   "type": "table-old",
   "description": "validator stats by public key over the lifetime of the validator process ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_balance{job=\"$validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") ",
     "legendFormat": "balance"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_proposals{job=\"$validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations{job=\"$validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\")  "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_aggregations{job=\"$validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_failed_attestations{job=\"$validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_failed_aggregations{job=\"$validator\"}), \"pubkey_short\", \"$1\", \"pubkey\", \"(.{10}).*\") "
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_balance{job=\"$validator\"}), \"pubkey\", \"$1\", \"pubkey_short\", \"(.{10}).*\") "
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{job=\"node-exporter\"})-sum(node_filesystem_avail_bytes{job=\"node-exporter\"}))/sum(node_filesystem_size_bytes{job=\"node-exporter\"})",
     "legendFormat": "disk usage"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Processor usage on the server",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",job=\"$host\"}[5m])) or sum(irate(node_cpu{mode=\"system\",job=\"$host\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=\"$host\"}[5m])) or sum(irate(node_cpu{mode=\"user\",job=\"$host\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",job=\"$host\"}[5m])) or sum(irate(node_cpu{mode=\"nice\",job=\"$host\"}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",job=\"$host\"}[5m])) or sum(irate(node_cpu{mode=\"iowait\",job=\"$host\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",job=\"$host\"}[5m])) or sum(irate(node_cpu{mode=\"steal\",job=\"$host\"}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",job=\"$host\"}[5m])) or sum(irate(node_cpu{mode=\"idle\",job=\"$host\"}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",job=\"$host\"}[5m])) or sum(irate(node_cpu{mode=\"irq\",job=\"$host\"}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",job=\"$host\"}[5m])) or sum(irate(node_cpu{mode=\"softirq\",job=\"$host\"}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",job=\"$host\"}[5m])) or sum(irate(node_cpu{mode=\"guest\",job=\"$host\"}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Monthly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"$validator\"}) - sum(validator_balance{job=\"$validator\"} offset 30d != 0) - (32 * count(validator_balance{job=\"$validator\"} > 16)) + (32 * count(validator_balance{job=\"$validator\"} offset 30d > 16))"
    }
   ]
  },
  {
   "title": "Weekly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"$validator\"}) - sum(validator_balance{job=\"$validator\"} offset 7d != 0) - (32 * count(validator_balance{job=\"$validator\"} > 16)) + (32 * count(validator_balance{job=\"$validator\"} offset 7d > 16))"
    }
   ]
  },
  {
   "title": "Daily Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"$validator\"}) - sum(validator_balance{job=\"$validator\"} offset 1d != 0) - (32 * count(validator_balance{job=\"$validator\"} > 16)) + (32 * count(validator_balance{job=\"$validator\"} offset 1d > 16))"
    }
   ]
  },
  {
   "title": "Hourly Earnings",
   "type": "singlestat",
   "description": "Increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance{job=\"$validator\"}) - sum(validator_balance{job=\"$validator\"} offset 1h != 0) - (32 * count(validator_balance{job=\"$validator\"} > 16)) + (32 * count(validator_balance{job=\"$validator\"} offset 1h > 16))"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 } },
  {
   "title": "Monthly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last month",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"$validator\"}) - sum(validator_balance{job=\"$validator\"} offset 30d != 0) - (32 * count(validator_balance{job=\"$validator\"} > 16)) +\t(32 * count(validator_balance{job=\"$validator\"} offset 30d > 16)))/(32 * avg_over_time(count(validator_balance{job=\"$validator\"} > 16)[30d:]))) * (365/30)",
     "legendFormat": "annualized monthly return"
    }
   ]
  },
  {
   "title": "Weekly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last week",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"$validator\"}) - sum(validator_balance{job=\"$validator\"} offset 7d != 0) - (32 * count(validator_balance{job=\"$validator\"} > 16)) +\t(32 * count(validator_balance{job=\"$validator\"} offset 7d > 16)))/(32 * avg_over_time(count(validator_balance{job=\"$validator\"} > 16)[7d:]))) * (365/7)",
     "legendFormat": "annualized weekly return"
    }
   ]
  },
  {
   "title": "Daily Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last day",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"$validator\"}) - sum(validator_balance{job=\"$validator\"} offset 1d != 0) - (32 * count(validator_balance{job=\"$validator\"} > 16)) +\t(32 * count(validator_balance{job=\"$validator\"} offset 1d > 16)))/(32 * avg_over_time(count(validator_balance{job=\"$validator\"} > 16)[1d:]))) * 365",
     "legendFormat": "annualized daily return"
    }
   ]
  },
  {
   "title": "Hourly Return, Annualized",
   "type": "singlestat",
   "description": "Percentage increase in all local validator balances over the last hour",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum(validator_balance{job=\"$validator\"}) - sum(validator_balance{job=\"$validator\"} offset 1h != 0) - (32 * count(validator_balance{job=\"$validator\"} > 16)) +\t(32 * count(validator_balance{job=\"$validator\"} offset 1h > 16)))/(32 * avg_over_time(count(validator_balance{job=\"$validator\"} > 16)[1h:]))) * 365 * 24",
     "legendFormat": "annualized hourly return"
    }
   ]
  },
  {
   "title": "Warn: The process just restarted",
   "type": "graph",
   "description": "This alert is useful only for people who has automatic restart of the process after crash. \nThis can be made for example by using the prysm.bat file on windows with \"set PRYSM_AUTORESTART=true&\", or with docker with \"--restart always\"",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"beacon node\"})/3600",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "(time()-process_start_time_seconds{job=\"validator\"})/3600"
    }
   ]
  },
  {
   "title": "Alert: 50 slots behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"beacon node\"}",
     "legendFormat": "beacon node"
    },
    {
     "expr": "up{job=\"validator\"}",
     "legendFormat": "validator"
    }
   ]
  },
  {
   "title": "Alert: Hourly earning <= 0",
   "type": "graph",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32",
     "legendFormat": "validators earning on 1h"
    }
   ]
  },
  {
   "title": "Alert: 50 errors  or 100 warns  in 1h",
   "type": "graph",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"error\"}[1h]) > 0) ",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Alert: Validator has been slashed",
   "type": "graph",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_statuses, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Alert: Participation rate < 66%",
   "type": "graph",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "beacon_prev_epoch_target_gwei/beacon_prev_epoch_active_gwei*100"
    }
   ]
  }
 ]
}