{
 "title": "SSV Operator Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "clustertag", "label": "clustertag", "query": { "query": "label_values(clustertag)" } }
  ]
 },
 "panels": [
  {
   "title": "General SSV Network Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validators Per Operator Limit",
     "type": "stat",
     "description": "maximum amount of validators an operator may manage",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssvnoms_ValidatorsPerOperatorLimit",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Earnings",
     "type": "stat",
     "description": "accumulated network fees not yet withdrawn.",
     "gridPos": { "h": 4, "w": 15, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ssvnoms_NetworkEarnings/ 1e18", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Network Fee",
     "type": "stat",
     "description": "current network fee $SSV tokens per block",
     "gridPos": { "h": 3, "w": 10, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ssvnoms_NetworkFee / 1e18", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Liquidation Threshold Period",
     "type": "stat",
     "description": "minimum duration (in blocks) which a cluster has to have sufficient balance (liquidation collateral) to not be liquidated",
     "gridPos": { "h": 3, "w": 12, "x": 10, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssvnoms_LiquidationThresholdPeriod",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Minimum Liquidation Collateral",
     "type": "stat",
     "description": "minimum amount which a cluster has to have sufficient balance (liquidation collateral) to not be liquidated",
     "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssvnoms_MinimumLiquidationCollateral/ 1e18",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Operator Fee Increase Limit",
     "type": "stat",
     "description": "maximum increase in percentage the operator can update his fee to",
     "gridPos": { "h": 4, "w": 6, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssvnoms_OperatorFeeIncreaseLimit",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Maximum Operator Fee",
     "type": "stat",
     "description": "maximum fee value (SSV/year)",
     "gridPos": { "h": 4, "w": 6, "x": 16, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssvnoms_MaximumOperatorFee/ 1e18",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Operator Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "SSV Operator active",
   "type": "stat",
   "description": "1 if active and 0 if not active",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ssvnoms_operator_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "is private",
   "type": "stat",
   "description": "Indication if operator is permissioned",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ssvnoms_operator_isPrivate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validator Count",
   "type": "stat",
   "description": "Operator Validator Count",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssvnoms_operator_validatorCount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Earnings in $SSV",
   "type": "stat",
   "description": "Operators outstanding earnings in $SSV tokens",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssvnoms_operator_balance/1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator fee",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "operator fee",
     "type": "stat",
     "description": "The fee charged by the operator (denominated as $SSV tokens per block)",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 93 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ssvnoms_operator_fee", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Operator declared fee",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "declaredFee_boolean",
     "type": "stat",
     "description": "is a fee declared ?",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssvnoms_operator_declaredFee_boolean",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "declaredFee_value",
     "type": "stat",
     "description": "the declared fee (not actual fee)",
     "gridPos": { "h": 4, "w": 11, "x": 4, "y": 94 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssvnoms_operator_declaredFee_value",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Window",
     "type": "stat",
     "description": "declaredFee_time2 - declaredFee_time1",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssvnoms_operator_declaredFee_time2 - ssvnoms_operator_declaredFee_time1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "declaredFee_time1",
     "type": "stat",
     "description": "the execution time window",
     "gridPos": { "h": 4, "w": 7, "x": 6, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssvnoms_operator_declaredFee_time1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "declaredFee_time2",
     "type": "stat",
     "description": "the execution time window",
     "gridPos": { "h": 4, "w": 8, "x": 13, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ssvnoms_operator_declaredFee_time2",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Metrics for cluster $clustertag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "clustertag"
  },
  {
   "title": "cluster_balance",
   "type": "timeseries",
   "description": "Clusters outstanding balance denominated in $SSV tokens",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ssvnoms_cluster_balance{clustertag=\"$clustertag\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_balance  in $SSV",
   "type": "stat",
   "description": "Clusters outstanding balance denominated in $SSV tokens",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssvnoms_cluster_balance{clustertag=\"$clustertag\"}/1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_burnRate",
   "type": "stat",
   "description": "The rate per block in which the account spends SSV",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssvnoms_cluster_burnRate{clustertag=\"$clustertag\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_burnRate in $SSV Token",
   "type": "stat",
   "description": "burnRate in $SSV Token",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssvnoms_cluster_burnRate{clustertag=\"$clustertag\"}/1000000000000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Balance",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{__name__=~\"^ssvnoms_validator_balance_.*\", clustertag=\"$clustertag\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "isLiquidated",
   "type": "stat",
   "description": "Indication if a cluster is liquidated",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssvnoms_cluster_isLiquidated{clustertag=\"$clustertag\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "isLiquidatable",
   "type": "stat",
   "description": "Indication if a cluster could be liquidated",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssvnoms_cluster_isLiquidatable{clustertag=\"$clustertag\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}