{
 "title": "Keys API",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(lido_keys_api_job_duration_seconds_bucket,exported_job)"
    }
   },
   {
    "name": "srModuleId",
    "label": "SR Module id",
    "query": {
     "query": "label_values(lido_keys_api_nonce_value, srModuleId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "App version",
   "type": "stat",
   "description": "version",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "build_info{name=\"lido-keys-api\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Env",
   "type": "stat",
   "description": "Environment",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "build_info{name=\"lido-keys-api\"}",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "Network name",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "build_info{name=\"lido-keys-api\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  { "title": "Keys update", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Block number",
   "type": "stat",
   "description": "Block number for which the last update was made.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lido_keys_api_last_block_number"
    }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "description": "Block timestamp for which the last ValidatorsRegistry update was made.",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - lido_keys_api_last_update_timestamp"
    }
   ]
  },
  {
   "title": "Nonce SR Module \"${srModuleId}\"",
   "type": "stat",
   "description": "Nonce of Staking Router module  during last update",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "repeat": "srModuleId",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lido_keys_api_nonce_value{srModuleId=\"${srModuleId}\"}"
    }
   ]
  },
  {
   "title": "Operators keys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "used/unused keys",
     "type": "table",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum by(operator, srModuleId, used) (lido_keys_api_keys_by_sr_module_and_operator{})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Block number",
   "type": "stat",
   "description": "Block number for which the last ValidatorsRegistry update was made",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lido_keys_api_validators_registry_last_block_number"
    }
   ]
  },
  {
   "title": "Last update",
   "type": "stat",
   "description": "Block timestamp for which the last ValidatorsRegistry update was mad",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - lido_keys_api_validators_registry_last_update_block_timestamp"
    }
   ]
  },
  {
   "title": "slot",
   "type": "stat",
   "description": "Slot for which the last ValidatorsRegistry update was made.",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lido_keys_api_validators_registry_last_slot"
    }
   ]
  },
  { "title": "HTTP response", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "HTTP response duration",
   "type": "heatmap",
   "description": "Node operator registry keys API response duration",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_duration_seconds_bucket[1m])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP requests by status code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(instance, statusCode) (increase(http_requests_duration_seconds_count[$__interval]))",
     "legendFormat": "{{statusCode}}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Job \"${job}\" duration",
     "type": "heatmap",
     "description": "The job duration",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "repeat": "job",
     "targets": [
      {
       "expr": "sum(rate(lido_keys_api_job_duration_seconds_bucket{exported_job=\"${job:raw}\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "Execution layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "EL requests duration",
   "type": "heatmap",
   "description": "The request duration to the EL RPC provider",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(el_rpc_requests_duration_seconds_bucket[1m])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "El request error ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(el_rpc_requests_duration_seconds_count{result=\"error\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Consensus layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CL requests duration",
   "type": "heatmap",
   "description": "The request duration to the CL API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(cl_api_requests_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CL requests errors",
   "type": "timeseries",
   "description": "Number of request errors to the CL API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(cl_api_requests_duration_seconds_count{result=\"error\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}