{
 "title": "Node.js",
 "description": "Monitor an application built using Node.js",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(nodejs_version_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "description": "The version of Node.js.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Node.js Restarts",
   "type": "stat",
   "description": "The number of times Node.js restarted.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{job=~\"$job\"}[$__range]))",
     "legendFormat": "Node.js"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "CPU usage.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(process_cpu_user_seconds_total{job=~\"$job\"}[$__interval]) * 100",
       "legendFormat": "User CPU - {{project}}"
      },
      {
       "expr": "irate(process_cpu_system_seconds_total{job=~\"$job\"}[$__interval]) * 100",
       "legendFormat": "System CPU - {{project}}"
      },
      {
       "expr": "irate(process_cpu_seconds_total{job=~\"$job\"}[$__interval]) * 100",
       "legendFormat": "Total CPU - {{project}}"
      }
     ]
    },
    {
     "title": "CPU Time Spent",
     "type": "timeseries",
     "description": "CPU time spent.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[$__interval])",
       "legendFormat": "{{project}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Memory usage.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=~\"$job\"}",
       "legendFormat": "Process Memory - {{project}}"
      },
      {
       "expr": "nodejs_heap_size_total_bytes{job=~\"$job\"}",
       "legendFormat": "Heap Total - {{project}}"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{job=~\"$job\"}",
       "legendFormat": "Heap Used - {{project}}"
      },
      {
       "expr": "nodejs_external_memory_bytes{job=~\"$job\"}",
       "legendFormat": "External Memory - {{project}}"
      }
     ]
    },
    {
     "title": "Active Handlers and Requests",
     "type": "timeseries",
     "description": "Number of active handle and active requests.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nodejs_active_handles_total{job=~\"$job\"}",
       "legendFormat": "Active Handler - {{project}}"
      },
      {
       "expr": "nodejs_active_requests_total{job=~\"$job\"}",
       "legendFormat": "Active Request - {{project}}"
      }
     ]
    },
    {
     "title": "Event Loop Latency",
     "type": "timeseries",
     "description": "Latency of the event loop.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_seconds{job=~\"$job\"}",
       "legendFormat": "Last - {{project}}"
      },
      {
       "expr": "nodejs_eventloop_lag_p99_seconds{job=~\"$job\"}",
       "legendFormat": "P99 - {{project}}"
      },
      {
       "expr": "nodejs_eventloop_lag_p50_seconds{job=~\"$job\"}",
       "legendFormat": "P50 - {{project}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Duration Rate",
   "type": "timeseries",
   "description": "Rate of garbage collection duration.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{job=~\"$job\"}[$__interval])",
     "legendFormat": "{{kind}} - {{project}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Duration of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_sum{job=~\"$job\"}",
     "legendFormat": "{{kind}} - {{project}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "Usage of heap memory.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\"}",
     "legendFormat": "Total - {{project}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\"}",
     "legendFormat": "Used - {{project}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "Resident - {{project}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\"}",
     "legendFormat": "External - {{project}}"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "description": "Rate of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{job=~\"$job\"}[$__interval])",
     "legendFormat": "{{kind}} - {{project}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "description": "Count of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{job=~\"$job\"}",
     "legendFormat": "{{kind}} - {{project}}"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "timeseries",
   "description": "Usage of heap space.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=~\"$job\"}",
     "legendFormat": "{{space}} - {{project}}"
    }
   ]
  }
 ]
}