{
 "title": "Besu Overview",
 "description": "Provides an overview of Besu nodes",
 "tags": [
  "besu",
  "ethereum"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System",
    "query": "query_result(ethereum_blockchain_height or besu_blockchain_height)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (besu_blockchain_height or ethereum_blockchain_height)",
     "legendFormat": "Chain Height"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_best_known_block or ethereum_best_known_block_number)"
    },
    {
     "expr": "sum by (instance) ((besu_synchronizer_best_known_block - besu_blockchain_height) or (ethereum_best_known_block_number - ethereum_blockchain_height))"
    },
    {
     "expr": "sum by (instance) (besu_blockchain_difficulty_total)",
     "legendFormat": "Total Difficulty"
    },
    {
     "expr": "sum by (instance) ((1/rate(besu_blockchain_height[5m])) or (1/rate(ethereum_blockchain_height[5m])))"
    },
    {
     "expr": "sum by (instance) (time() - besu_blockchain_chain_head_timestamp)"
    },
    {
     "expr": "sum by (instance) (besu_peers_peer_count_current or ethereum_peer_count)",
     "legendFormat": "Peer Count"
    },
    {
     "expr": "sum by (instance) ((besu_peers_peer_count_current / besu_network_peers_limit) or ethereum_peer_count / ethereum_peer_limit)"
    }
   ]
  },
  {
   "title": "Fast Sync Progress",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (instance) ((besu_blockchain_height or ethereum_blockchain_height) and besu_synchronizer_world_state_pending_requests_current > 0)",
     "legendFormat": "Chain Height"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_fast_sync_pivot_block_current and besu_synchronizer_world_state_pending_requests_current > 0)"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_fast_sync_pivot_block_current - besu_blockchain_height and besu_synchronizer_world_state_pending_requests_current > 0)"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_world_state_pending_requests_current > 0)"
    },
    {
     "expr": "sum by (instance) (besu_synchronizer_world_state_completed_requests_total and besu_synchronizer_world_state_pending_requests_current > 0)"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "1/rate(besu_blockchain_height[5m]) or 1/rate(ethereum_blockchain_height[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Blocks Behind",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "besu_synchronizer_best_known_block - besu_blockchain_height or ethereum_best_known_block_number - ethereum_blockchain_height",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU Time IRate [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\"} + ignoring(area) jvm_memory_bytes_used{area=\"nonheap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}