{
 "title": "SSV Operator Node",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "explorer",
    "query": "https://explorer.stage.ssv.network,https://explorer.ssv.network"
   },
   { "name": "validator_dashboard_id", "query": "XIbEQ37aa" }
  ]
 },
 "panels": [
  { "title": "Validators Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validators (Attestation)",
   "type": "table",
   "description": "Information on attestation duties for all validators registered to an operator",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 1 },
   "targets": [
    { "expr": "ssv:validator:ibft_stage" },
    {
     "expr": "ssv:validator:ibft_highest_decided"
    },
    { "expr": "ssv:network:connected_peers" },
    {
     "expr": "ssv:validator:ibft_current_sequence"
    },
    { "expr": "ssv:validator:ibft_round" },
    {
     "expr": "ssv:validator:running_ibfts_count"
    },
    {
     "expr": "ssv:validator:ibft_current_slot"
    },
    { "expr": "ssv:validator:status" }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Connections Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ssv:network:all_connected_peers",
     "legendFormat": "Connections"
    }
   ]
  },
  { "title": "Node Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Current Health Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ssv:beacon:node_status", "legendFormat": "Beacon" },
    { "expr": "ssv:eth1:node_status", "legendFormat": "ETH1" },
    { "expr": "ssv:node_status", "legendFormat": "SSV Operator" },
    {}
   ]
  },
  {
   "title": "Operator Node Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "ssv:node_status", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "ETH1 Node Health",
   "type": "timeseries",
   "description": "Status of the connected ETH1 node",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 24 },
   "targets": [
    { "expr": "ssv:eth1:node_status" }
   ]
  },
  {
   "title": "Beacon Node Health",
   "type": "timeseries",
   "description": "Status of the connected beacon node",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 24 },
   "targets": [
    { "expr": "ssv:beacon:node_status" }
   ]
  },
  { "title": "Process Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{ pod }}" }
   ]
  }
 ]
}