{
 "title": "Lodestar - validator monitor",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Validators connected",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validator_monitor_validators_total"
    },
    { "expr": "validator_monitor_validators" }
   ]
  },
  {
   "title": "Connected validators",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "1 - validator_monitor_prev_epoch_on_chain_attester_correct_head_total",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "balance delta prev epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(\n  delta(validator_monitor_prev_epoch_on_chain_balance_total[32m])\n)",
     "legendFormat": "balance_delta"
    },
    {
     "expr": "avg(\n  delta(validator_monitor_prev_epoch_on_chain_balance[32m])\n)",
     "legendFormat": "balance_delta_new"
    }
   ]
  },
  {
   "title": "Wrong head ratio",
   "type": "timeseries",
   "description": "Percent of attestations having correct head.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_attester_incorrect_head_total[$rate_interval])\n/\nrate(validator_monitor_prev_epoch_on_chain_attester_hit_total[$rate_interval])",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Avg inclusion distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "inclusion distance"
    },
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_inclusion_distance_sum[$rate_interval])\n/\nrate(validator_monitor_prev_epoch_on_chain_inclusion_distance_count[$rate_interval])",
     "legendFormat": "inclusion distance new"
    }
   ]
  },
  {
   "title": "prev epoch miss ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(delta(validator_monitor_prev_epoch_on_chain_attester_miss_total[$rate_interval]))\n/\n(\n  sum(delta(validator_monitor_prev_epoch_on_chain_attester_hit_total[$rate_interval]))\n  +\n  sum(delta(validator_monitor_prev_epoch_on_chain_attester_miss_total[$rate_interval]))\n) > 0",
     "legendFormat": "attester"
    },
    {
     "expr": "sum(delta(validator_monitor_prev_epoch_on_chain_target_attester_miss_total[$rate_interval]))\n/\n(\n  sum(delta(validator_monitor_prev_epoch_on_chain_target_attester_hit_total[$rate_interval]))\n  +\n  sum(delta(validator_monitor_prev_epoch_on_chain_target_attester_miss_total[$rate_interval]))\n) > 0",
     "legendFormat": "target"
    },
    {
     "expr": "sum(delta(validator_monitor_prev_epoch_on_chain_head_attester_miss_total[$rate_interval]))\n/\n(\n  sum(delta(validator_monitor_prev_epoch_on_chain_head_attester_hit_total[$rate_interval]))\n  +\n  sum(delta(validator_monitor_prev_epoch_on_chain_head_attester_miss_total[$rate_interval]))\n) > 0",
     "legendFormat": "head"
    }
   ]
  },
  {
   "title": "Prev epoch min delay",
   "type": "timeseries",
   "description": "Min delay from when the validator should send an object and when it was received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(delta(validator_monitor_prev_epoch_attestations_min_delay_seconds_sum[$rate_interval]))\n/\nsum(delta(validator_monitor_prev_epoch_attestations_min_delay_seconds_count[$rate_interval]))",
     "legendFormat": "attestations"
    },
    {
     "expr": "sum(delta(validator_monitor_prev_epoch_aggregates_min_delay_seconds_sum[$rate_interval]))\n/\nsum(delta(validator_monitor_prev_epoch_aggregates_min_delay_seconds_count[$rate_interval]))",
     "legendFormat": "aggregates"
    },
    {
     "expr": "sum(delta(validator_monitor_prev_epoch_beacon_blocks_min_delay_seconds_sum[$rate_interval]))\n/\nsum(delta(validator_monitor_prev_epoch_beacon_blocks_min_delay_seconds_count[$rate_interval]))"
    }
   ]
  },
  {
   "title": "Inclusion distance distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "32*12*rate(validator_monitor_prev_epoch_on_chain_inclusion_distance_bucket [$rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Inclusion distance distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "count(validator_monitor_prev_epoch_on_chain_inclusion_distance == 1) / count(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "1"
    },
    {
     "expr": "count(validator_monitor_prev_epoch_on_chain_inclusion_distance == 2) / count(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "2"
    },
    {
     "expr": "count(5 > validator_monitor_prev_epoch_on_chain_inclusion_distance >= 3) / count(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "3-5"
    },
    {
     "expr": "count(10 > validator_monitor_prev_epoch_on_chain_inclusion_distance >= 5) / count(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "5-10"
    },
    {
     "expr": "count(validator_monitor_prev_epoch_on_chain_inclusion_distance >= 10) / count(validator_monitor_prev_epoch_on_chain_inclusion_distance)",
     "legendFormat": "+10"
    }
   ]
  },
  {
   "title": "Inclusion distance distribution > 1",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "32*12*rate(validator_monitor_prev_epoch_on_chain_inclusion_distance_bucket [$rate_interval]) - 10000",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Attestater sent per epoch per validator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(validator_monitor_prev_epoch_attestations_total)/sum(validator_monitor_validators_total)",
     "legendFormat": "attestations_sent"
    },
    {
     "expr": "sum(validator_monitor_prev_epoch_aggregates_total)/sum(validator_monitor_validators_total)",
     "legendFormat": "aggregates_sent"
    }
   ]
  },
  {
   "title": "Attestation inclusions epoch per validator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(validator_monitor_prev_epoch_attestation_block_inclusions_total)",
     "legendFormat": "block_inclusions"
    },
    {
     "expr": "avg(validator_monitor_prev_epoch_attestation_aggregate_inclusions_total)",
     "legendFormat": "aggregate_inclusions"
    },
    {
     "expr": "validator_monitor_prev_epoch_attestation_block_inclusions_sum\n/\nvalidator_monitor_prev_epoch_attestation_block_inclusions_count",
     "legendFormat": "block_inclusions new"
    },
    {
     "expr": "validator_monitor_prev_epoch_attestation_aggregate_inclusions_sum\n/\nvalidator_monitor_prev_epoch_attestation_aggregate_inclusions_count",
     "legendFormat": "aggregate_inclusions new"
    }
   ]
  },
  {
   "title": "Block proposer balance delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(validator_monitor_proposer_balance_delta_known_gwei_sum[32m])\n/\nrate(validator_monitor_proposer_balance_delta_known_gwei_count[32m])",
     "legendFormat": "known_avg"
    },
    {
     "expr": "rate(lodestar_proposer_balance_delta_any_gwei_sum[32m])\n/\nrate(lodestar_proposer_balance_delta_any_gwei_count[32m])",
     "legendFormat": "all_avg"
    },
    {
     "expr": "histogram_quantile(0.25, sum(rate(lodestar_proposer_balance_delta_any_gwei_bucket[32m])) by (le))",
     "legendFormat": "all_q25"
    },
    {
     "expr": "histogram_quantile(0.10, sum(rate(lodestar_proposer_balance_delta_any_gwei_bucket[32m])) by (le))",
     "legendFormat": "all_q10"
    }
   ]
  }
 ]
}