{
 "title": "Lodestar validator client",
 "tags": [ "lodestar" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "ByJob" }
  ]
 },
 "panels": [
  {
   "title": "Published messages / slot (expect blocks)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "12 * rate(vc_published_sync_committee_message_total[$__rate_interval])",
     "legendFormat": "sync_committee_message"
    },
    {
     "expr": "12 * rate(vc_published_sync_committee_contribution_total[32m])",
     "legendFormat": "sync_committee_contribution"
    },
    {
     "expr": "12 * rate(vc_published_attestations_total[32m])",
     "legendFormat": "attestations"
    },
    {
     "expr": "12 * rate(vc_published_aggregates_total[32m])",
     "legendFormat": "aggregates"
    }
   ]
  },
  {
   "title": "Lodestar version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_version{job=\"lodestar_validator\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{job=\"lodestar_validator\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lodestar_version{job=\"lodestar_validator\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "VC indices",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vc_indices_count" }
   ]
  },
  {
   "title": "Process heap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_heap_bytes{job=\"lodestar_validator\"}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{job=\"lodestar_validator\"}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 }, "options": { "content": "_Validator metrics =D_" } },
  {
   "title": "Step times diff (except block)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "deriv(vc_attester_step_call_produce_attestation_seconds_sum[32m])\n/\nrate(vc_attester_step_call_produce_attestation_seconds_count[32m])",
     "legendFormat": "call_produce_attestation"
    },
    {
     "expr": "deriv(vc_attester_step_call_publish_attestation_seconds_sum[32m])\n/\nrate(vc_attester_step_call_publish_attestation_seconds_count[32m])",
     "legendFormat": "call_publish_attestation"
    },
    {
     "expr": "deriv(vc_attester_step_call_produce_aggregate_seconds_sum[32m])\n/\nrate(vc_attester_step_call_produce_aggregate_seconds_count[32m])",
     "legendFormat": "call_produce_aggregate"
    },
    {
     "expr": "deriv(vc_attester_step_call_publish_aggregate_seconds_sum[32m])\n/\nrate(vc_attester_step_call_publish_aggregate_seconds_count[32m])",
     "legendFormat": "call_publish_aggregate"
    },
    {
     "expr": "deriv(vc_sync_committee_step_call_produce_message_seconds_sum[32m])\n/\nrate(vc_sync_committee_step_call_produce_message_seconds_count[32m])",
     "legendFormat": "call_produce_sync_message"
    },
    {
     "expr": "deriv(vc_sync_committee_step_call_publish_message_seconds_sum[32m])\n/\nrate(vc_sync_committee_step_call_publish_message_seconds_count[32m])",
     "legendFormat": "call_publish_sync_message"
    },
    {
     "expr": "deriv(vc_sync_committee_step_call_produce_aggregate_seconds_sum[32m])\n/\nrate(vc_sync_committee_step_call_produce_aggregate_seconds_count[32m])",
     "legendFormat": "call_produce_sync_aggregate"
    },
    {
     "expr": "deriv(vc_sync_committee_step_call_publish_aggregate_seconds_sum[32m])\n/\nrate(vc_sync_committee_step_call_publish_aggregate_seconds_count[32m])",
     "legendFormat": "call_publish_sync_aggregate"
    }
   ]
  },
  {
   "title": "Step times diff (block only)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "deriv(vc_proposer_step_call_produce_block_seconds_sum[$__rate_interval])\n/\nrate(vc_proposer_step_call_produce_block_seconds_count[$__rate_interval])",
     "legendFormat": "call_produce_block"
    },
    {
     "expr": "deriv(vc_proposer_step_call_publish_block_seconds_sum[$__rate_interval])\n/\nrate(vc_proposer_step_call_publish_block_seconds_count[$__rate_interval])",
     "legendFormat": "call_publish_block"
    }
   ]
  },
  {
   "title": "Publish attestation diff from slot 1/3",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(vc_attester_step_call_publish_attestation_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Publish aggregate diff from slot 2/3",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(vc_attester_step_call_publish_aggregate_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Publish sync committee message diff from slot 1/3",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(vc_sync_committee_step_call_publish_message_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Publish block diff from slot 0/3",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(vc_proposer_step_call_publish_block_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "vc REST API request times",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vc_rest_api_client_request_time_seconds_sum[32m])\n/\nrate(vc_rest_api_client_request_time_seconds_count[32m])",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "beacon REST API response times",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lodestar_api_rest_response_time_seconds_sum[32m])\n/\nrate(lodestar_api_rest_response_time_seconds_count[32m])",
     "legendFormat": "{{operationId}}"
    }
   ]
  },
  {
   "title": "Block produced, published, errored",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "delta(vc_block_produced_total[$__rate_interval])",
     "legendFormat": "block produced"
    },
    {
     "expr": "delta(vc_block_published_total[$__rate_interval])",
     "legendFormat": "block published"
    },
    {
     "expr": "rate(vc_block_proposing_errors_total[$__rate_interval])",
     "legendFormat": "block proposing errors {{error}}"
    }
   ]
  },
  {
   "title": "Local sign time share of CPU time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(vc_local_sign_time_seconds_sum[32m])"
    }
   ]
  },
  {
   "title": "Local sign avg sec / signature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vc_local_sign_time_seconds_sum[32m])\n/\nrate(vc_local_sign_time_seconds_count[32m])"
    }
   ]
  },
  {
   "title": "Local sign time per signature heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(vc_local_sign_time_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Duties data structures size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "vc_sync_committee_duties_count", "legendFormat": "sync_committee_duties_epochs" },
    { "expr": "vc_proposer_duties_epoch_count", "legendFormat": "proposer_duties_epochs" },
    { "expr": "vc_attester_duties_epoch_count", "legendFormat": "attester_duties_epochs" },
    { "expr": "vc_attester_duties_count", "legendFormat": "attester_duties" }
   ]
  },
  {
   "title": "Duties reorgs / sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(vc_proposer_duties_reorg_total[$__rate_interval])",
     "legendFormat": "proposer duties"
    },
    {
     "expr": "rate(vc_attestation_duties_reorg_total[$__rate_interval])",
     "legendFormat": "attestation duties"
    },
    {
     "expr": "rate(vc_sync_committee_duties_reorg_total[$__rate_interval])",
     "legendFormat": "sync committee duties"
    }
   ]
  }
 ]
}